package com.lemon.spring.enumeretion.audit;

public enum AutoActive {
     ACTIVE_ON_CREATE,ACTIVE_ON_UPDATE
    ,INACTIVE_ON_CREATE,INACTIVE_ON_UPDATE
    ,ALWAYS_ACTIVE,ALWAYS_INACTIVE
    ,NONE
    ,ACTIVE_IF_HAS_ANY_ROLE,ACTIVE_IF_HAS_ROLE,ACTIVE_IF_HAS_NO_ROLE,ACTIVE_IF_HAS_NO_ANY_ROLE
    ,INACTIVE_IF_HAS_ANY_ROLE,INACTIVE_IF_HAS_ROLE,INACTIVE_IF_HAS_NO_ROLE,INACTIVE_IF_HAS_NO_ANY_ROLE
    ,ACTIVE_IF_HAS_ANY_ROLE_ON_CREATE,ACTIVE_IF_HAS_ROLE_ON_CREATE,ACTIVE_IF_HAS_NO_ROLE_ON_CREATE,ACTIVE_IF_HAS_NO_ANY_ROLE_ON_CREATE
    ,INACTIVE_IF_HAS_ANY_ROLE_ON_CREATE,INACTIVE_IF_HAS_ROLE_ON_CREATE,INACTIVE_IF_HAS_NO_ROLE_ON_CREATE,INACTIVE_IF_HAS_NO_ANY_ROLE_ON_CREATE
    ,ACTIVE_IF_HAS_ANY_ROLE_ON_UPDATE,ACTIVE_IF_HAS_ROLE_ON_UPDATE,ACTIVE_IF_HAS_NO_ROLE_ON_UPDATE,ACTIVE_IF_HAS_NO_ANY_ROLE_ON_UPDATE
    ,INACTIVE_IF_HAS_ANY_ROLE_ON_UPDATE,INACTIVE_IF_HAS_ROLE_ON_UPDATE,INACTIVE_IF_HAS_NO_ROLE_ON_UPDATE,INACTIVE_IF_HAS_NO_ANY_ROLE_ON_UPDATE
}
